### PR TITLE
GUAC-62 Frontend refactor

### PR DESCRIPTION
**Pull request by Pot4ssium**
- Refactored the front end, split out the constant values drizzled everywhere into universal constants and stored in data folder.
- Fixed redundant logic for inventory management such as adding resources
- Fixed displaying inventory logic and the arrows for pagination
- Separating background into a different scene
- Re code all of the pop ups into individual scenes
- Clean out the main file to only call scenes
- Moved miner's logic into Miner.ts class instead of main
- Implemented smelters and crafters

### CODE REVIEW

**Comment by mosguinz** [comment]
Please address the linting error and appoint reviewers when complete.

**Comment by mosguinz** [comment]
@yan-chan Your latest merge failed multiple CI tests. Please address them prior to merging.

CI tests are not enforced for non-master PRs. However, they should not be ignored unless you sure that the changes you made are deliberate.

**Comment by yan-chan** [comment]
Fixed.

**Comment by mosguinz** [comment]
Closed by #67.

**Pull request closed without merging**
